// 📦 Shipment Types
exports.SHIPMENT_TYPES = {
  AIR_FREIGHT: 'AIR_FREIGHT',
  SEA_FREIGHT: 'SEA_FREIGHT',
  EXPRESS_COURIER: 'EXPRESS_COURIER'
};

// 📦 Product Types
exports.PRODUCT_TYPES = {
  GENERAL_MERCHANDISE: 'GENERAL_MERCHANDISE',
  ELECTRONICS: 'ELECTRONICS',
  TEXTILES: 'TEXTILES',
  FOOD: 'FOOD',
  CHEMICALS: 'CHEMICALS',
  PHARMACEUTICALS: 'PHARMACEUTICALS',
  MACHINERY: 'MACHINERY',
  FURNITURE: 'FURNITURE',
  AUTO_PARTS: 'AUTO_PARTS',
  PERISHABLE: 'PERISHABLE'
};

// 📦 Package Types
exports.PACKAGE_TYPES = {
  CARTONS: 'CARTONS',
  PALLETS: 'PALLETS',
  CRATES: 'CRATES',
  DRUMS: 'DRUMS',
  ROLLS: 'ROLLS',
  BUNDLES: 'BUNDLES',
  CONTAINER: 'CONTAINER',
  LOOSE: 'LOOSE'
};

// 📦 Shipping Modes
exports.SHIPPING_MODES = {
  DDP: 'DDP',
  DDU: 'DDU'
};

// 📦 Booking Status
exports.BOOKING_STATUS = {
  REQUESTED: 'BOOKING_REQUESTED',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
  QUOTED: 'QUOTED'
};

// 📦 Shipment Status
exports.SHIPMENT_STATUS = {
  BOOKING_REQUESTED: 'BOOKING_REQUESTED',
  CONFIRMED: 'CONFIRMED',
  RECEIVED_AT_WAREHOUSE: 'RECEIVED_AT_WAREHOUSE',
  CONSOLIDATION_IN_PROGRESS: 'CONSOLIDATION_IN_PROGRESS',
  LOADED: 'LOADED',
  IN_TRANSIT: 'IN_TRANSIT',
  ARRIVED: 'ARRIVED_AT_DESTINATION',
  CUSTOMS_CLEARANCE: 'CUSTOMS_CLEARANCE',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED'
};

// 📦 Countries
exports.COUNTRIES = {
  THAILAND: 'THAILAND',
  CHINA: 'CHINA',
  USA: 'USA',
  UK: 'UK',
  CANADA: 'CANADA'
};

// 📦 Currencies
exports.CURRENCIES = {
  USD: 'USD',
  GBP: 'GBP',
  CAD: 'CAD',
  THB: 'THB',
  CNY: 'CNY'
};